version: '3.8'

services:
  mysql-office:
    image: mysql:8.0.41-debian
    container_name: mysql-office
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_arsip
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - office_net

  redis-office:
    image: redis:latest
    container_name: redis-office
    restart: unless-stopped
    ports:
      - "6370:6379"
    networks:
      - office_net

volumes:
  mysql_data:

networks:
  office_net:
    driver: bridge
